ui testing scheleton
MUHC-DP-Project/pbrn-ui pull request #4
Opened 2020-11-20 00:50 UTC by iyatan

2020-11-20 05:36 UTC, preyansh98 approved these changes
LGTM! Can we also add package-lock.json to .gitignore?

2020-11-20 06:14 UTC, nathlemma approved these changes

2020-11-20 14:59 UTC, ahmedazz260 requested changes, later dismissed
Good job,

just be sure to add package-lock.json like preyansh mentioned

2020-11-20 14:59 UTC, ahmedazz260 commented on .gitignore
> +
please add  to the list: 
package-lock.json

2020-11-27 23:56 UTC, preyansh98 commented
@ahmedazz260 you can merge this in as the new changes have been done

2020-11-28 08:39 UTC, merged