Update README.md
MUHC-DP-Project/pbrn-ui pull request #5
Opened 2020-11-20 01:47 UTC by preyansh98

## Description

Updated Readme for repository

## Related Issue

https://github.com/MUHC-DP-Project/muhc-gateway/issues/3

## How Has This Been Tested

N/A

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-11-21 12:00 UTC, ahmedazz260 requested changes, later dismissed

2020-11-21 12:00 UTC, ahmedazz260 commented on README.md
> +Welcome to the frontend of MUHC microservices suite. This project is the sole frontend client for the web app of the MUHC project by this GitHub organization.
PRBN-UI suite is the sole frontend client for the web app of the  PRBN project by this Github organization

2020-11-22 21:27 UTC, iyatan submitted a review, later dismissed

2020-11-22 22:12 UTC, Carl-Elkhoury approved these changes
LGTM

2020-11-22 23:21 UTC, merged